---

- name: devops.repos
  src: https://github.com/hmcts/repos-role.git
  scm: git
  version: master

- name: devops.common
  src: https://github.com/hmcts/common-role.git
  scm: git
  version: master
