---
- name: Define java package names
  set_fact:
    javapkg_main: "java-{{ java.version }}-openjdk"
    javapkg_devel: "java-{{ java.version }}-openjdk-devel"
    javapkg_headless: "java-{{ java.version }}-openjdk-headless"

- name: Force specific version of java packages when requested
  set_fact:
     javapkg_main: "java-{{ java.version }}-openjdk-{{ java.minver }}"
     javapkg_devel: "java-{{ java.version }}-openjdk-devel-{{ java.minver }}"
     javapkg_headless: "java-{{ java.version }}-openjdk-headless-{{ java.minver }}"
  when: "java.minver is defined"

- name: Show Java version which has been requested
  debug:
    msg: "java={{ java }}"

- name: Show name of the Java packages that are going to be installed
  debug:
    msg: "javapkg_main={{ javapkg_main }} + javapkg_devel={{ javapkg_devel}} + javapkg_headless={{ javapkg_headless }}"

- name: install java packages
  become: yes
  yum:
    name:
      - "{{ javapkg_main }}"
      - "{{ javapkg_devel }}"
      - "{{ javapkg_headless }}"
    state: installed
    allow_downgrade: true
